name: eagle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ufs2arco=0.17.1
  - "esmf=8.7.0=nompi*"
  - pip
  - pip:
      - torch<2.7
      - anemoi-datasets==0.5.26
      - anemoi-graphs==0.6.6
      - anemoi-models==0.9.5
      - anemoi-training==0.6.5
      - anemoi-inference==0.7.3
      - anemoi-utils==0.4.37
      - anemoi-transform==0.1.17
      - eagle-tools
